/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorIndexRouteImport } from './routes/advisor.index'
import { Route as AdvisorReportRouteImport } from './routes/advisor.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/advisor/',
  path: '/advisor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorReportRoute = AdvisorReportRouteImport.update({
  id: '/advisor/report',
  path: '/advisor/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor/report': typeof AdvisorReportRoute
  '/advisor/': typeof AdvisorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor/report': typeof AdvisorReportRoute
  '/advisor': typeof AdvisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor/report': typeof AdvisorReportRoute
  '/advisor/': typeof AdvisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advisor/report' | '/advisor/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advisor/report' | '/advisor'
  id: '__root__' | '/' | '/advisor/report' | '/advisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorReportRoute: typeof AdvisorReportRoute
  AdvisorIndexRoute: typeof AdvisorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/advisor'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/report': {
      id: '/advisor/report'
      path: '/advisor/report'
      fullPath: '/advisor/report'
      preLoaderRoute: typeof AdvisorReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorReportRoute: AdvisorReportRoute,
  AdvisorIndexRoute: AdvisorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
